import { NormalizedProjectConfig } from '../types/index.js';
import { DependencyRegistry } from '../registry/dependency.js';
import { createStructifyManifest } from '../manifest/index.js';
import { createComposableGenerationPlan } from '../generation/composable.js';
import { getPredefinedTemplateFiles } from './predefined/index.js';

export interface GeneratedTemplateFile {
  path: string;
  content: string;
}

export function getStarterTemplates(config: NormalizedProjectConfig): GeneratedTemplateFile[] {
  return createComposableGenerationPlan(config).files;
}

export function getLegacyStarterTemplates(
  config: NormalizedProjectConfig,
): GeneratedTemplateFile[] {
  const files: GeneratedTemplateFile[] = [];
  const mode = config.mode;
  const isFrontend = mode === 'frontend-only' || mode === 'fullstack';
  const isBackend = mode === 'backend-only' || mode === 'fullstack';

  // Base Package Manifest & Configs
  const dependencies: Record<string, string> = {};
  const devDependencies: Record<string, string> = {};
  const scripts: Record<string, string> = {
    test: 'vitest run',
  };

  // Base package.json structure
  const rootFiles: GeneratedTemplateFile[] = [
    {
      path: 'README.md',
      content: `# ${config.projectName}\n\nGenerated with Structify Developer Productivity Platform.\n`,
    },
    {
      path: '.gitignore',
      content: `node_modules\ndist\n.env\n.env.local\n.env.development.local\n.env.test.local\n.env.production.local\n.vercel\n.next\n`,
    },
    {
      path: '.editorconfig',
      content: `root = true\n\n[*]\nindent_style = space\nindent_size = 2\nend_of_line = lf\ncharset = utf-8\ntrim_trailing_whitespace = true\ninsert_final_newline = true\n`,
    },
    {
      path: 'structify.config.json',
      content: JSON.stringify(
        {
          ...config,
          structify: {
            version: '1.0.0',
            generatedBy: 'structify',
            manifestPath: 'structify.manifest.json',
          },
        },
        null,
        2,
      ),
    },
  ];

  files.push(...rootFiles);

  // Setup Specific Stacks
  if (isFrontend) {
    const fe = config.stack.frontend;
    if (fe === 'next') {
      scripts.dev = 'next dev';
      scripts.build = 'next build';
      scripts.start = 'next start';
      dependencies.next = '^15.0.0';
      dependencies.react = '^19.0.0';
      dependencies['react-dom'] = '^19.0.0';
      devDependencies.typescript = '^5.0.0';
      devDependencies['@types/react'] = '^19.0.0';
      devDependencies['@types/react-dom'] = '^19.0.0';

      files.push(
        {
          path: 'next.config.ts',
          content: `import type { NextConfig } from "next";\n\nconst nextConfig: NextConfig = {};\n\nexport default nextConfig;\n`,
        },
        {
          path: 'tsconfig.json',
          content: `{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}\n`,
        },
        {
          path: 'app/layout.tsx',
          content: `import type { Metadata } from "next";\nimport "./globals.css";\n\nexport const metadata: Metadata = {\n  title: "${config.projectName}",\n  description: "Generated by Structify",\n};\n\nexport default function RootLayout({\n  children,\n}: Readonly<{\n  children: React.ReactNode;\n}>) {\n  return (\n    <html lang="en">\n      <body>{children}</body>\n    </html>\n  );\n}\n`,
        },
        {
          path: 'app/page.tsx',
          content: `export default function Home() {\n  return (\n    <main className="flex min-h-screen flex-col items-center justify-center p-24">\n      <h1 className="text-4xl font-bold">Welcome to ${config.projectName}</h1>\n      <p className="mt-4 text-xl">Generated with Structify</p>\n    </main>\n  );\n}\n`,
        },
        {
          path: 'app/globals.css',
          content: `body {\n  margin: 0;\n  font-family: sans-serif;\n}\n`,
        },
      );
    } else if (fe === 'vite-react') {
      scripts.dev = 'vite';
      scripts.build = 'tsc && vite build';
      scripts.preview = 'vite preview';
      dependencies.react = '^19.0.0';
      dependencies['react-dom'] = '^19.0.0';
      devDependencies.vite = '^6.0.0';
      devDependencies['@vitejs/plugin-react'] = '^4.3.0';
      devDependencies.typescript = '^5.0.0';
      devDependencies['@types/react'] = '^19.0.0';
      devDependencies['@types/react-dom'] = '^19.0.0';

      files.push(
        {
          path: 'vite.config.ts',
          content: `import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\n\nexport default defineConfig({\n  plugins: [react()],\n});\n`,
        },
        {
          path: 'tsconfig.json',
          content: `{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["DOM", "DOM.Iterable", "ES2020"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "strict": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src"]
}\n`,
        },
        {
          path: 'index.html',
          content: `<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8" />\n    <title>${config.projectName}</title>\n  </head>\n  <body>\n    <div id="root"></div>\n    <script type="module" src="/src/main.tsx"></script>\n  </body>\n</html>\n`,
        },
        {
          path: 'src/main.tsx',
          content: `import { StrictMode } from 'react';\nimport { createRoot } from 'react-dom/client';\nimport App from './App.tsx';\nimport './index.css';\n\ncreateRoot(document.getElementById('root')!).render(\n  <StrictMode>\n    <App />\n  </StrictMode>,\n);\n`,
        },
        {
          path: 'src/App.tsx',
          content: `export default function App() {\n  return (\n    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100vh' }}>\n      <h1>Welcome to ${config.projectName}</h1>\n      <p>Generated with Structify React Vite</p>\n    </div>\n  );\n}\n`,
        },
        {
          path: 'src/index.css',
          content: `body {\n  margin: 0;\n  font-family: sans-serif;\n}\n`,
        },
      );
    }
  }

  if (isBackend) {
    const be = config.stack.backend;
    if (be === 'express') {
      if (isFrontend) {
        scripts['dev:web'] = scripts.dev;
        scripts['dev:api'] = 'ts-node-dev src/index.ts';
        scripts.dev = 'npm run dev:web';
        scripts['build:api'] = 'tsc --project tsconfig.server.json';
      } else {
        scripts.dev = 'ts-node-dev src/index.ts';
        scripts.build = 'tsc';
        scripts.start = 'node dist/index.js';
      }
      dependencies.express = '^4.19.0';
      devDependencies.typescript = '^5.0.0';
      devDependencies['ts-node-dev'] = '^2.0.0';
      devDependencies['@types/express'] = '^4.17.0';
      devDependencies['@types/node'] = '^20.0.0';

      files.push(
        {
          path: isFrontend ? 'tsconfig.server.json' : 'tsconfig.json',
          content: `{
  "compilerOptions": {
    "target": "es2022",
    "module": "commonjs",
    "lib": ["es2022"],
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": ["src/**/*"]
}\n`,
        },
        {
          path: 'src/config/env.ts',
          content: `export const ENV = {\n  PORT: process.env.PORT || 3000,\n  NODE_ENV: process.env.NODE_ENV || 'development',\n};\n`,
        },
        {
          path: 'src/middleware/error.middleware.ts',
          content: `import { Request, Response, NextFunction } from 'express';\n\nexport function errorHandler(err: unknown, _req: Request, res: Response, _next: NextFunction) {\n  const message = err instanceof Error ? err.message : 'Internal Server Error';\n  if (err instanceof Error && err.stack) {\n    console.error(err.stack);\n  }\n  res.status(500).json({\n    success: false,\n    error: message,\n  });\n}\n`,
        },
        {
          path: 'src/routes/health.route.ts',
          content: `import { Router } from 'express';\n\nexport const healthRouter = Router();\nhealthRouter.get('/health', (req, res) => {\n  res.json({ status: 'ok', timestamp: new Date() });\n});\n`,
        },
        {
          path: 'src/app.ts',
          content: `import express from 'express';\nimport { healthRouter } from './routes/health.route.js';\nimport { errorHandler } from './middleware/error.middleware.js';\n\nexport const app = express();\napp.use(express.json());\napp.use('/api', healthRouter);\napp.use(errorHandler);\n`,
        },
        {
          path: 'src/index.ts',
          content: `import { app } from './app.js';\nimport { ENV } from './config/env.js';\n\napp.listen(ENV.PORT, () => {\n  console.log(\`Server running on http://localhost:\${ENV.PORT} in \${ENV.NODE_ENV} mode\`);\n});\n`,
        },
      );
    } else if (be === 'nest') {
      if (isFrontend) {
        scripts['dev:web'] = scripts.dev;
        scripts['dev:api'] = 'nest start --watch';
        scripts.dev = 'npm run dev:web';
        scripts['build:api'] = 'nest build';
      } else {
        scripts.dev = 'nest start --watch';
        scripts.build = 'nest build';
        scripts.start = 'nest start';
      }
      dependencies['@nestjs/common'] = '^10.0.0';
      dependencies['@nestjs/core'] = '^10.0.0';
      dependencies['reflect-metadata'] = '^0.2.0';
      dependencies.rxjs = '^7.8.0';
      devDependencies.typescript = '^5.0.0';
      devDependencies['@types/node'] = '^20.0.0';
      devDependencies['@nestjs/cli'] = '^10.0.0';

      files.push(
        {
          path: 'tsconfig.json',
          content: `{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2021",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false
  }
}\n`,
        },
        {
          path: 'src/app.service.ts',
          content: `import { Injectable } from '@nestjs/common';\n\n@Injectable()\nexport class AppService {\n  getHello(): string {\n    return 'Hello from NestJS (generated by Structify)!';\n  }\n}\n`,
        },
        {
          path: 'src/app.controller.ts',
          content: `import { Controller, Get } from '@nestjs/common';\nimport { AppService } from './app.service.js';\n\n@Controller()\nexport class AppController {\n  constructor(private readonly appService: AppService) {}\n\n  @Get()\n  getHello(): string {\n    return this.appService.getHello();\n  }\n}\n`,
        },
        {
          path: 'src/app.module.ts',
          content: `import { Module } from '@nestjs/common';\nimport { AppController } from './app.controller.js';\nimport { AppService } from './app.service.js';\n\n@Module({\n  imports: [],\n  controllers: [AppController],\n  providers: [AppService],\n})\nexport class AppModule {}\n`,
        },
        {
          path: 'src/main.ts',
          content: `import { NestFactory } from '@nestjs/core';\nimport { AppModule } from './app.module.js';\n\nasync function bootstrap() {\n  const app = await NestFactory.create(AppModule);\n  await app.listen(3000);\n  console.log('Application is running on: http://localhost:3000');\n}\nbootstrap();\n`,
        },
      );
    }
  }

  // Styling (Tailwind / MUI)
  if (isFrontend) {
    const style = config.stack.styling;
    const fe = config.stack.frontend;
    if (style === 'tailwind') {
      devDependencies.tailwindcss = '^3.4.0';
      devDependencies.postcss = '^8.4.0';
      devDependencies.autoprefixer = '^10.4.0';

      files.push(
        {
          path: 'tailwind.config.js',
          content: `/** @type {import('tailwindcss').Config} */\nmodule.exports = {\n  content: [\n    "./app/**/*.{js,ts,jsx,tsx}",\n    "./src/**/*.{js,ts,jsx,tsx}",\n    "./index.html"\n  ],\n  theme: {\n    extend: {},\n  },\n  plugins: [],\n};\n`,
        },
        {
          path: 'postcss.config.js',
          content: `module.exports = {\n  plugins: {\n    tailwindcss: {},\n    autoprefixer: {},\n  },\n};\n`,
        },
      );

      // Inject tailwind imports to main CSS
      if (fe === 'next') {
        const cssFile = files.find((f) => f.path === 'app/globals.css');
        if (cssFile) {
          cssFile.content =
            `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\n` + cssFile.content;
        }
      } else if (fe === 'vite-react') {
        const cssFile = files.find((f) => f.path === 'src/index.css');
        if (cssFile) {
          cssFile.content =
            `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\n` + cssFile.content;
        }
      }
    } else if (style === 'mui') {
      dependencies['@mui/material'] = '^6.0.0';
      dependencies['@emotion/react'] = '^11.11.0';
      dependencies['@emotion/styled'] = '^11.11.0';

      files.push({
        path: 'src/theme.ts',
        content: `import { createTheme } from '@mui/material/styles';\n\nexport const theme = createTheme({\n  palette: {\n    mode: 'light',\n    primary: {\n      main: '#2563eb',\n    },\n  },\n});\n`,
      });

      // Example integration inside App / page
      if (fe === 'vite-react') {
        const mainFile = files.find((f) => f.path === 'src/main.tsx');
        if (mainFile) {
          mainFile.content = `import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport { ThemeProvider } from '@mui/material/styles';\nimport CssBaseline from '@mui/material/CssBaseline';\nimport App from './App.tsx';\nimport { theme } from './theme.ts';\nimport './index.css';\n\nReactDOM.createRoot(document.getElementById('root')!).render(\n  <React.StrictMode>\n    <ThemeProvider theme={theme}>\n      <CssBaseline />\n      <App />\n    </ThemeProvider>\n  </React.StrictMode>,\n);\n`;
        }
        const appFile = files.find((f) => f.path === 'src/App.tsx');
        if (appFile && !config.templateId) {
          appFile.content = `import { Container, Typography, Button, Box } from '@mui/material';\n\nexport default function App() {\n  return (\n    <Container maxWidth="sm">\n      <Box sx={{ my: 4, display: 'flex', flexDirection: 'column', alignItems: 'center' }}>\n        <Typography variant="h4" component="h1" gutterBottom>\n          Welcome to ${config.projectName}\n        </Typography>\n        <Typography color="text.secondary">\n          Styling with Material UI enabled.\n        </Typography>\n        <Button variant="contained" color="primary" sx={{ mt: 3 }}>\n          Material UI Button\n        </Button>\n      </Box>\n    </Container>\n  );\n}\n`;
        }
      } else if (fe === 'next') {
        files.push({
          path: 'app/providers.tsx',
          content: `'use client';\n\nimport CssBaseline from '@mui/material/CssBaseline';\nimport { ThemeProvider } from '@mui/material/styles';\nimport { theme } from '../src/theme';\n\nexport function Providers({ children }: Readonly<{ children: React.ReactNode }>) {\n  return (\n    <ThemeProvider theme={theme}>\n      <CssBaseline />\n      {children}\n    </ThemeProvider>\n  );\n}\n`,
        });
        const layoutFile = files.find((f) => f.path === 'app/layout.tsx');
        if (layoutFile) {
          layoutFile.content = `import type { Metadata } from "next";\nimport { Providers } from "./providers";\nimport "./globals.css";\n\nexport const metadata: Metadata = {\n  title: "${config.projectName}",\n  description: "Generated by Structify",\n};\n\nexport default function RootLayout({\n  children,\n}: Readonly<{\n  children: React.ReactNode;\n}>) {\n  return (\n    <html lang="en">\n      <body>\n        <Providers>{children}</Providers>\n      </body>\n    </html>\n  );\n}\n`;
        }
        if (!config.templateId) {
          files.push({
            path: 'app/page.tsx',
            content: `'use client';\nimport { Container, Typography, Button, Box } from '@mui/material';\n\nexport default function Home() {\n  return (\n    <Container maxWidth="sm">\n      <Box sx={{ my: 4, display: 'flex', flexDirection: 'column', alignItems: 'center' }}>\n        <Typography variant="h4" component="h1" gutterBottom>\n          Welcome to ${config.projectName}\n        </Typography>\n        <Typography color="text.secondary">\n          Styling with Material UI enabled.\n        </Typography>\n        <Button variant="contained" color="primary" sx={{ mt: 3 }}>\n          Material UI Button\n        </Button>\n      </Box>\n    </Container>\n  );\n}\n`,
          });
        }
      }
    }
  }

  // Database / ORM Starters
  const db = config.stack.database;
  const orm = config.stack.orm;
  if (db === 'postgres' && orm === 'prisma') {
    devDependencies.prisma = '^5.15.0';
    dependencies['@prisma/client'] = '^5.15.0';
    scripts['db:generate'] = 'prisma generate';
    scripts['db:migrate'] = 'prisma migrate dev';
    scripts['db:studio'] = 'prisma studio';

    files.push(
      {
        path: 'prisma/schema.prisma',
        content: `datasource db {\n  provider = "postgresql"\n  url      = env("DATABASE_URL")\n}\n\ngenerator client {\n  provider = "prisma-client-js"\n}\n\nmodel User {\n  id    Int     @id @default(autoincrement())\n  email String  @unique\n  name  String?\n}\n`,
      },
      {
        path: 'src/db/prisma.ts',
        content: `import { PrismaClient } from '@prisma/client';\n\nconst globalForPrisma = global as unknown as { prisma: PrismaClient };\n\nexport const prisma =\n  globalForPrisma.prisma ||\n  new PrismaClient({\n    log: ['query'],\n  });\n\nif (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = prisma;\n`,
      },
      {
        path: '.env.example',
        content: `DATABASE_URL="postgresql://johndoe:randompassword@localhost:5432/mydb?schema=public"\n`,
      },
    );
  } else if (db === 'mongodb' && orm === 'mongoose') {
    dependencies.mongoose = '^8.4.0';
    devDependencies['@types/node'] = '^20.0.0';

    files.push(
      {
        path: 'src/db/mongoose.ts',
        content: `import mongoose from 'mongoose';\n\nconst MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/mydb';\n\nexport async function connectDB() {\n  try {\n    await mongoose.connect(MONGODB_URI);\n    console.log('MongoDB Connected Successfully');\n  } catch (error) {\n    console.error('MongoDB connection failure:', error);\n    process.exit(1);\n  }\n}\n`,
      },
      {
        path: 'src/models/example.model.ts',
        content: `import { Schema, model } from 'mongoose';\n\ninterface IUser {\n  name: string;\n  email: string;\n}\n\nconst userSchema = new Schema<IUser>({\n  name: { type: String, required: true },\n  email: { type: String, required: true, unique: true },\n});\n\nexport const User = model<IUser>('User', userSchema);\n`,
      },
      {
        path: '.env.example',
        content: `MONGODB_URI="mongodb://localhost:27017/mydb"\n`,
      },
    );
  }

  // Tooling integrations (Docker, CI, Husky)
  if (config.tools.docker) {
    files.push(
      {
        path: 'Dockerfile',
        content: `FROM node:20-alpine\nWORKDIR /app\nCOPY package.json package-lock.json* ./\nRUN npm install\nCOPY . .\nRUN npm run build\nEXPOSE 3000\nCMD ["npm", "run", "start"]\n`,
      },
      {
        path: 'docker-compose.yml',
        content: `version: '3.8'\nservices:\n  app:\n    build: .\n    ports:\n      - "3000:3000"\n    environment:\n      - NODE_ENV=production\n`,
      },
    );
  }

  if (config.tools.eslint) {
    devDependencies.eslint = '^8.56.0';
    devDependencies['@typescript-eslint/parser'] = '^6.21.0';
    devDependencies['@typescript-eslint/eslint-plugin'] = '^6.21.0';
    scripts.lint =
      config.stack.frontend === 'next'
        ? 'eslint "app/**/*.{ts,tsx}"'
        : 'eslint "src/**/*.{ts,tsx}"';

    files.push({
      path: '.eslintrc.json',
      content: `{\n  "root": true,\n  "parser": "@typescript-eslint/parser",\n  "plugins": ["@typescript-eslint"],\n  "extends": [\n    "eslint:recommended",\n    "plugin:@typescript-eslint/recommended"\n  ],\n  "rules": {\n    "@typescript-eslint/no-unused-vars": [\n      "error",\n      {\n        "argsIgnorePattern": "^_",\n        "varsIgnorePattern": "^_"\n      }\n    ]\n  }\n}\n`,
    });
  }

  if (config.tools.prettier) {
    devDependencies.prettier = '^3.2.0';
    scripts.format =
      config.stack.frontend === 'next'
        ? 'prettier --write "app/**/*.{ts,tsx,css,html,json}"'
        : 'prettier --write "src/**/*.{ts,tsx,css,html,json}"';

    files.push({
      path: '.prettierrc',
      content: `{\n  "semi": true,\n  "singleQuote": true,\n  "tabWidth": 2,\n  "trailingComma": "all"\n}\n`,
    });
  }

  if (config.tools.githubActions) {
    files.push({
      path: '.github/workflows/ci.yml',
      content: `name: CI\n\non:\n  push:\n    branches: [main]\n  pull_request:\n    branches: [main]\n\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 20\n          cache: npm\n      - run: npm install\n      - run: npm run lint\n        if: hashFiles('.eslintrc.json') != ''\n      - run: npm run build\n`,
    });
  }

  if (config.tools.husky) {
    devDependencies.husky = '^9.0.0';
    scripts.prepare = 'husky';
    files.push({
      path: '.husky/README.md',
      content: `# Husky\n\nStructify generated Husky configuration metadata only. Run \`npm install\` and configure hooks when ready.\n`,
    });
  }

  if (config.tools.lintStaged) {
    devDependencies['lint-staged'] = '^15.2.0';
    files.push({
      path: '.lintstagedrc.json',
      content: `{\n  "*.{ts,tsx,js,jsx,json,md,css}": [\n    "prettier --write"\n  ]\n}\n`,
    });
  }

  if (config.tools.commitlint) {
    devDependencies['@commitlint/cli'] = '^19.0.0';
    devDependencies['@commitlint/config-conventional'] = '^19.0.0';
    files.push({
      path: 'commitlint.config.js',
      content: `module.exports = { extends: ['@commitlint/config-conventional'] };\n`,
    });
  }

  if (!files.some((file) => file.path === '.env.example')) {
    files.push({
      path: '.env.example',
      content: isBackend
        ? `PORT=3000\nNODE_ENV=development\n`
        : `NEXT_PUBLIC_APP_NAME="${config.projectName}"\n`,
    });
  }

  // Final package.json output merging all resolved dependencies
  const resolvedDependencies = resolveDependencies(
    dependencies,
    devDependencies,
    config.stack.packageManager,
  );

  const packageJsonContent = {
    name: config.projectName.toLowerCase(),
    version: '1.0.0',
    private: true,
    scripts,
    dependencies: resolvedDependencies.dependencies,
    devDependencies: resolvedDependencies.devDependencies,
  };

  files.push({
    path: 'package.json',
    content: JSON.stringify(packageJsonContent, null, 2) + '\n',
  });

  if (config.templateId) {
    const fe = config.stack.frontend;
    const style = config.stack.styling;
    const templateFiles = getPredefinedTemplateFiles(
      config.templateId,
      fe,
      style,
      config.projectName,
      {
        backend: config.stack.backend,
        database: config.stack.database,
        orm: config.stack.orm,
      },
    );
    for (const tf of templateFiles) {
      const existing = files.find((f) => f.path === tf.path);
      if (existing) {
        existing.content = tf.content;
      } else {
        files.push(tf);
      }
    }
  }

  files.push({
    path: 'structify.manifest.json',
    content:
      JSON.stringify(
        createStructifyManifest({
          config,
          templatePaths: files.map((file) => file.path),
        }),
        null,
        2,
      ) + '\n',
  });

  return files;
}

function resolveDependencies(
  dependencies: Record<string, string>,
  devDependencies: Record<string, string>,
  packageManager: 'npm',
): { dependencies: Record<string, string>; devDependencies: Record<string, string> } {
  const registry = new DependencyRegistry();
  for (const [packageName, versionRange] of Object.entries(dependencies)) {
    registry.register({
      packageName,
      versionRange,
      dependencyType: 'prod',
      supportedPackageManagers: ['npm'],
      installScope: 'root',
      reason: 'Phase 6 deterministic template dependency',
    });
  }
  for (const [packageName, versionRange] of Object.entries(devDependencies)) {
    registry.register({
      packageName,
      versionRange,
      dependencyType: 'dev',
      supportedPackageManagers: ['npm'],
      installScope: 'root',
      reason: 'Phase 6 deterministic template development dependency',
    });
  }

  const { conflicts } = registry.deduplicateAndResolveConflicts();
  if (conflicts.length > 0) {
    throw new Error(
      `Dependency version conflict detected: ${conflicts
        .map((conflict) => `${conflict.packageName} (${conflict.versions.join(', ')})`)
        .join('; ')}`,
    );
  }

  const grouped = registry.groupByPackageManagerAndWorkspace(packageManager).root ?? {
    prod: [],
    dev: [],
  };
  return {
    dependencies: Object.fromEntries(grouped.prod.map(splitPackageSpec)),
    devDependencies: Object.fromEntries(grouped.dev.map(splitPackageSpec)),
  };
}

function splitPackageSpec(spec: string): [string, string] {
  const atIndex = spec.lastIndexOf('@');
  return [spec.slice(0, atIndex), spec.slice(atIndex + 1)];
}
