import { PredefinedTemplateDefinition } from '../types.js';
import { commonBackendFiles, createBackendPackageJson, createReadme } from './helpers.js';

export const expressRestApiTemplate: PredefinedTemplateDefinition = {
  metadata: {
    id: 'express-rest-api',
    name: 'Express REST API',
    category: 'backend',
    description:
      'Production-ready Express REST API with controllers, routes, services, middleware, config, health checks, and TypeScript tooling.',
    supportedFrameworks: ['express'],
    supportedStyling: ['none'],
    defaultFramework: 'express',
    defaultStyling: 'none',
    generatedFiles: ['src/index.ts', 'src/app.ts', 'src/controllers', 'src/routes'],
    enabledFeatures: { eslint: true, prettier: true },
    scripts: { dev: 'tsx watch src/index.ts', build: 'tsc', lint: 'eslint "src/**/*.ts"' },
    verificationExpectations: ['npm run build', 'npm run lint', 'GET /api/health'],
    sections: ['Health endpoint', 'User routes', 'Controllers', 'Services', 'Middleware'],
    components: ['App', 'HealthController', 'UserController', 'ErrorHandler', 'RequestLogger'],
    layoutType: 'Modular REST API',
    successSummary: 'Generated Express REST API starter.',
  },
  backendDefinition: {
    files: ({ projectName }) => [
      ...commonBackendFiles(
        projectName,
        createReadme(projectName, 'A modular Express REST API generated by Structify.', [
          'GET /api/health',
          'GET /api/users',
          'GET /api/users/:id',
        ]),
      ),
      {
        path: 'package.json',
        content: createBackendPackageJson({
          projectName,
          description: 'Structify Express REST API starter',
          scripts: {},
          dependencies: { cors: '^2.8.5', dotenv: '^16.4.7', express: '^4.21.2', helmet: '^7.2.0' },
          devDependencies: { '@types/cors': '^2.8.17', '@types/express': '^4.17.21' },
        }),
      },
      {
        path: 'src/config/env.ts',
        content: `import dotenv from 'dotenv';

dotenv.config();

export const env = {
  nodeEnv: process.env.NODE_ENV ?? 'development',
  port: Number(process.env.PORT ?? 3000),
  appName: process.env.APP_NAME ?? '${projectName}',
};
`,
      },
      {
        path: 'src/utils/async-handler.ts',
        content: `import { NextFunction, Request, Response } from 'express';

export function asyncHandler(
  handler: (req: Request, res: Response, next: NextFunction) => Promise<void>,
) {
  return (req: Request, res: Response, next: NextFunction) => {
    void handler(req, res, next).catch(next);
  };
}
`,
      },
      {
        path: 'src/utils/api-error.ts',
        content: `export class ApiError extends Error {
  constructor(
    public readonly statusCode: number,
    public readonly code: string,
    message: string,
  ) {
    super(message);
  }
}
`,
      },
      {
        path: 'src/middleware/request-logger.ts',
        content: `import { NextFunction, Request, Response } from 'express';

export function requestLogger(req: Request, res: Response, next: NextFunction) {
  const startedAt = Date.now();
  res.on('finish', () => {
    const duration = Date.now() - startedAt;
    console.log(\`\${req.method} \${req.originalUrl} \${res.statusCode} \${duration}ms\`);
  });
  next();
}
`,
      },
      {
        path: 'src/middleware/not-found.ts',
        content: `import { NextFunction, Request, Response } from 'express';
import { ApiError } from '../utils/api-error.js';

export function notFound(req: Request, _res: Response, next: NextFunction) {
  next(new ApiError(404, 'ROUTE_NOT_FOUND', \`Route \${req.method} \${req.originalUrl} was not found\`));
}
`,
      },
      {
        path: 'src/middleware/error-handler.ts',
        content: `import { NextFunction, Request, Response } from 'express';
import { ApiError } from '../utils/api-error.js';

export function errorHandler(
  error: Error,
  req: Request,
  res: Response,
  _next: NextFunction,
) {
  const statusCode = error instanceof ApiError ? error.statusCode : 500;
  const code = error instanceof ApiError ? error.code : 'INTERNAL_SERVER_ERROR';
  res.status(statusCode).json({
    error: { code, message: error.message || 'Internal server error' },
    requestId: req.headers['x-request-id'] ?? 'local',
  });
}
`,
      },
      {
        path: 'src/services/health.service.ts',
        content: `import { env } from '../config/env.js';
import { HealthStatus } from '../interfaces/health.interface.js';

export class HealthService {
  getStatus(): HealthStatus {
    return {
      status: 'ok',
      uptime: process.uptime(),
      timestamp: new Date().toISOString(),
      service: env.appName,
    };
  }
}
`,
      },
      {
        path: 'src/services/user.service.ts',
        content: `export interface UserDto {
  id: string;
  name: string;
  role: 'admin' | 'member';
}

const users: UserDto[] = [
  { id: 'usr_001', name: 'Demo Admin', role: 'admin' },
  { id: 'usr_002', name: 'Demo Member', role: 'member' },
];

export class UserService {
  listUsers() {
    return users;
  }

  findUser(id: string) {
    return users.find((user) => user.id === id);
  }
}
`,
      },
      {
        path: 'src/controllers/health.controller.ts',
        content: `import { Request, Response } from 'express';
import { HealthService } from '../services/health.service.js';

const healthService = new HealthService();

export function getHealth(req: Request, res: Response) {
  res.json({ data: healthService.getStatus(), requestId: req.headers['x-request-id'] ?? 'local' });
}
`,
      },
      {
        path: 'src/controllers/user.controller.ts',
        content: `import { Request, Response } from 'express';
import { UserService } from '../services/user.service.js';
import { ApiError } from '../utils/api-error.js';

const userService = new UserService();

export function listUsers(req: Request, res: Response) {
  res.json({ data: userService.listUsers(), requestId: req.headers['x-request-id'] ?? 'local' });
}

export function getUser(req: Request, res: Response) {
  const userId = req.params.id;
  if (!userId) {
    throw new ApiError(400, 'USER_ID_REQUIRED', 'User id is required.');
  }
  const user = userService.findUser(userId);
  if (!user) {
    throw new ApiError(404, 'USER_NOT_FOUND', 'User was not found.');
  }
  res.json({ data: user, requestId: req.headers['x-request-id'] ?? 'local' });
}
`,
      },
      {
        path: 'src/routes/health.routes.ts',
        content: `import { Router } from 'express';
import { getHealth } from '../controllers/health.controller.js';

export const healthRouter = Router();

healthRouter.get('/health', getHealth);
`,
      },
      {
        path: 'src/routes/user.routes.ts',
        content: `import { Router } from 'express';
import { getUser, listUsers } from '../controllers/user.controller.js';
import { asyncHandler } from '../utils/async-handler.js';

export const userRouter = Router();

userRouter.get('/users', listUsers);
userRouter.get('/users/:id', asyncHandler(async (req, res) => getUser(req, res)));
`,
      },
      {
        path: 'src/routes/index.ts',
        content: `import { Router } from 'express';
import { healthRouter } from './health.routes.js';
import { userRouter } from './user.routes.js';

export const apiRouter = Router();

apiRouter.use(healthRouter);
apiRouter.use(userRouter);
`,
      },
      {
        path: 'src/app.ts',
        content: `import cors from 'cors';
import express from 'express';
import helmet from 'helmet';
import { errorHandler } from './middleware/error-handler.js';
import { notFound } from './middleware/not-found.js';
import { requestLogger } from './middleware/request-logger.js';
import { apiRouter } from './routes/index.js';

export function createApp() {
  const app = express();
  app.use(helmet());
  app.use(cors());
  app.use(express.json());
  app.use(requestLogger);
  app.use('/api', apiRouter);
  app.use(notFound);
  app.use(errorHandler);
  return app;
}
`,
      },
      {
        path: 'src/index.ts',
        content: `import { createServer } from 'node:http';
import { createApp } from './app.js';
import { env } from './config/env.js';

const server = createServer(createApp());

server.listen(env.port, () => {
  console.log(\`\${env.appName} listening on http://localhost:\${env.port}\`);
});

for (const signal of ['SIGINT', 'SIGTERM']) {
  process.on(signal, () => {
    server.close(() => process.exit(0));
  });
}
`,
      },
    ],
  },
};
