import { PredefinedTemplateDefinition } from '../types.js';
import { commonBackendFiles, createBackendPackageJson, createReadme } from './helpers.js';

export const fastifyApiTemplate: PredefinedTemplateDefinition = {
  metadata: {
    id: 'fastify-api',
    name: 'Fastify API',
    category: 'backend',
    description:
      'Fastify API starter with plugin architecture, schemas, validation, route modules, controllers, logger, config, and centralized errors.',
    supportedFrameworks: ['fastify'],
    supportedStyling: ['none'],
    defaultFramework: 'fastify',
    defaultStyling: 'none',
    generatedFiles: ['src/server.ts', 'src/plugins', 'src/routes', 'src/controllers'],
    enabledFeatures: { eslint: true, prettier: true },
    scripts: { dev: 'tsx watch src/index.ts', build: 'tsc', lint: 'eslint "src/**/*.ts"' },
    verificationExpectations: ['npm run build', 'npm run lint', 'GET /api/health'],
    sections: ['Plugins', 'Schemas', 'Routes', 'Controllers', 'Error handler'],
    components: ['Server', 'HealthRoutes', 'ProjectRoutes', 'ErrorPlugin', 'Config'],
    layoutType: 'Fastify Plugin API',
    successSummary: 'Generated Fastify API starter.',
  },
  backendDefinition: {
    files: ({ projectName }) => [
      ...commonBackendFiles(
        projectName,
        createReadme(projectName, 'A high-performance Fastify API generated by Structify.', [
          'GET /api/health',
          'GET /api/projects',
          'GET /api/projects/:id',
        ]),
      ),
      {
        path: 'package.json',
        content: createBackendPackageJson({
          projectName,
          description: 'Structify Fastify API starter',
          scripts: {},
          dependencies: { dotenv: '^16.4.7', fastify: '^4.28.1' },
        }),
      },
      {
        path: 'src/config/env.ts',
        content: `import dotenv from 'dotenv';

dotenv.config();

export const env = {
  nodeEnv: process.env.NODE_ENV ?? 'development',
  port: Number(process.env.PORT ?? 3000),
  appName: process.env.APP_NAME ?? '${projectName}',
};
`,
      },
      {
        path: 'src/schemas/project.schema.ts',
        content: `export const projectParamsSchema = {
  type: 'object',
  required: ['id'],
  properties: {
    id: { type: 'string', minLength: 1 },
  },
} as const;

export const projectResponseSchema = {
  type: 'object',
  properties: {
    data: {
      type: 'object',
      properties: {
        id: { type: 'string' },
        name: { type: 'string' },
        status: { type: 'string' },
      },
    },
    requestId: { type: 'string' },
  },
} as const;
`,
      },
      {
        path: 'src/services/health.service.ts',
        content: `import { env } from '../config/env.js';

export function getHealthStatus() {
  return {
    status: 'ok' as const,
    uptime: process.uptime(),
    timestamp: new Date().toISOString(),
    service: env.appName,
  };
}
`,
      },
      {
        path: 'src/services/project.service.ts',
        content: `export interface Project {
  id: string;
  name: string;
  status: 'active' | 'paused';
}

const projects: Project[] = [
  { id: 'prj_001', name: 'Demo API', status: 'active' },
  { id: 'prj_002', name: 'Internal Portal', status: 'paused' },
];

export function listProjects() {
  return projects;
}

export function findProject(id: string) {
  return projects.find((project) => project.id === id);
}
`,
      },
      {
        path: 'src/controllers/health.controller.ts',
        content: `import { FastifyReply, FastifyRequest } from 'fastify';
import { getHealthStatus } from '../services/health.service.js';

export async function getHealth(request: FastifyRequest, reply: FastifyReply) {
  return reply.send({ data: getHealthStatus(), requestId: request.id });
}
`,
      },
      {
        path: 'src/controllers/project.controller.ts',
        content: `import { FastifyReply, FastifyRequest } from 'fastify';
import { findProject, listProjects } from '../services/project.service.js';

export async function getProjects(request: FastifyRequest, reply: FastifyReply) {
  return reply.send({ data: listProjects(), requestId: request.id });
}

export async function getProject(
  request: FastifyRequest<{ Params: { id: string } }>,
  reply: FastifyReply,
) {
  const project = findProject(request.params.id);
  if (!project) {
    return reply.code(404).send({
      error: { code: 'PROJECT_NOT_FOUND', message: 'Project was not found.' },
      requestId: request.id,
    });
  }
  return reply.send({ data: project, requestId: request.id });
}
`,
      },
      {
        path: 'src/plugins/error-handler.ts',
        content: `import { FastifyPluginAsync } from 'fastify';

export const errorHandlerPlugin: FastifyPluginAsync = async (app) => {
  app.setErrorHandler((error, request, reply) => {
    request.log.error(error);
    reply.status(error.statusCode ?? 500).send({
      error: {
        code: error.code ?? 'INTERNAL_SERVER_ERROR',
        message: error.message,
      },
      requestId: request.id,
    });
  });
};
`,
      },
      {
        path: 'src/plugins/health-plugin.ts',
        content: `import { FastifyPluginAsync } from 'fastify';
import { healthRoutes } from '../routes/health.routes.js';

export const healthPlugin: FastifyPluginAsync = async (app) => {
  await app.register(healthRoutes, { prefix: '/health' });
};
`,
      },
      {
        path: 'src/routes/health.routes.ts',
        content: `import { FastifyPluginAsync } from 'fastify';
import { getHealth } from '../controllers/health.controller.js';

export const healthRoutes: FastifyPluginAsync = async (app) => {
  app.get('/', getHealth);
};
`,
      },
      {
        path: 'src/routes/project.routes.ts',
        content: `import { FastifyPluginAsync } from 'fastify';
import { getProject, getProjects } from '../controllers/project.controller.js';
import { projectParamsSchema, projectResponseSchema } from '../schemas/project.schema.js';

export const projectRoutes: FastifyPluginAsync = async (app) => {
  app.get('/projects', getProjects);
  app.get('/projects/:id', {
    schema: {
      params: projectParamsSchema,
      response: { 200: projectResponseSchema },
    },
    handler: getProject,
  });
};
`,
      },
      {
        path: 'src/server.ts',
        content: `import fastify from 'fastify';
import { errorHandlerPlugin } from './plugins/error-handler.js';
import { healthPlugin } from './plugins/health-plugin.js';
import { projectRoutes } from './routes/project.routes.js';

export async function buildServer() {
  const app = fastify({ logger: true });
  await app.register(errorHandlerPlugin);
  await app.register(healthPlugin, { prefix: '/api' });
  await app.register(projectRoutes, { prefix: '/api' });
  return app;
}
`,
      },
      {
        path: 'src/index.ts',
        content: `import { env } from './config/env.js';
import { buildServer } from './server.js';

const app = await buildServer();

try {
  await app.listen({ port: env.port, host: '0.0.0.0' });
} catch (error) {
  app.log.error(error);
  process.exit(1);
}

for (const signal of ['SIGINT', 'SIGTERM']) {
  process.on(signal, () => {
    void app.close().then(() => process.exit(0));
  });
}
`,
      },
    ],
  },
};
