import { PredefinedTemplateDefinition } from '../types.js';
import { commonBackendFiles, createBackendPackageJson, createReadme } from './helpers.js';

export const honoApiTemplate: PredefinedTemplateDefinition = {
  metadata: {
    id: 'hono-api',
    name: 'Hono API',
    category: 'backend',
    description:
      'Modern lightweight Hono API with route modules, middleware, validation helpers, config, utilities, and health endpoint.',
    supportedFrameworks: ['hono'],
    supportedStyling: ['none'],
    defaultFramework: 'hono',
    defaultStyling: 'none',
    generatedFiles: ['src/index.ts', 'src/app.ts', 'src/routes', 'src/middleware'],
    enabledFeatures: { eslint: true, prettier: true },
    scripts: { dev: 'tsx watch src/index.ts', build: 'tsc', lint: 'eslint "src/**/*.ts"' },
    verificationExpectations: ['npm run build', 'npm run lint', 'GET /api/health'],
    sections: ['Route modules', 'Middleware', 'Validation utilities', 'Config', 'Health endpoint'],
    components: ['App', 'HealthRoutes', 'TaskRoutes', 'RequestIdMiddleware', 'Validator'],
    layoutType: 'Hono Modular API',
    successSummary: 'Generated Hono API starter.',
  },
  backendDefinition: {
    files: ({ projectName }) => [
      ...commonBackendFiles(
        projectName,
        createReadme(projectName, 'A lightweight Hono API generated by Structify.', [
          'GET /api/health',
          'GET /api/tasks',
          'POST /api/tasks',
        ]),
      ),
      {
        path: 'package.json',
        content: createBackendPackageJson({
          projectName,
          description: 'Structify Hono API starter',
          scripts: {},
          dependencies: {
            '@hono/node-server': '^1.13.7',
            dotenv: '^16.4.7',
            hono: '^4.6.14',
          },
        }),
      },
      {
        path: 'src/config/env.ts',
        content: `import dotenv from 'dotenv';

dotenv.config();

export const env = {
  nodeEnv: process.env.NODE_ENV ?? 'development',
  port: Number(process.env.PORT ?? 3000),
  appName: process.env.APP_NAME ?? '${projectName}',
};
`,
      },
      {
        path: 'src/utils/validation.ts',
        content: `export function requireString(value: unknown, field: string): string {
  if (typeof value !== 'string' || value.trim().length === 0) {
    throw new Error(\`\${field} is required.\`);
  }
  return value.trim();
}
`,
      },
      {
        path: 'src/middleware/request-id.ts',
        content: `import { createMiddleware } from 'hono/factory';

export const requestIdMiddleware = createMiddleware(async (context, next) => {
  const requestId = context.req.header('x-request-id') ?? crypto.randomUUID();
  context.set('requestId', requestId);
  context.header('x-request-id', requestId);
  await next();
});
`,
      },
      {
        path: 'src/middleware/error-handler.ts',
        content: `import { ErrorHandler } from 'hono';

export const errorHandler: ErrorHandler = (error, context) => {
  const requestId = context.get('requestId') ?? 'local';
  return context.json(
    {
      error: {
        code: 'REQUEST_ERROR',
        message: error.message || 'Internal server error',
      },
      requestId,
    },
    500,
  );
};
`,
      },
      {
        path: 'src/services/health.service.ts',
        content: `import { env } from '../config/env.js';

export function getHealthStatus() {
  return {
    status: 'ok' as const,
    uptime: process.uptime(),
    timestamp: new Date().toISOString(),
    service: env.appName,
  };
}
`,
      },
      {
        path: 'src/services/task.service.ts',
        content: `export interface Task {
  id: string;
  title: string;
  completed: boolean;
}

const tasks: Task[] = [
  { id: 'tsk_001', title: 'Replace demo task data', completed: false },
];

export function listTasks() {
  return tasks;
}

export function createTask(title: string) {
  const task = {
    id: \`tsk_\${String(tasks.length + 1).padStart(3, '0')}\`,
    title,
    completed: false,
  };
  tasks.push(task);
  return task;
}
`,
      },
      {
        path: 'src/routes/health.routes.ts',
        content: `import { Hono } from 'hono';
import { getHealthStatus } from '../services/health.service.js';

export const healthRoutes = new Hono();

healthRoutes.get('/', (context) =>
  context.json({ data: getHealthStatus(), requestId: context.req.header('x-request-id') ?? 'local' }),
);
`,
      },
      {
        path: 'src/routes/task.routes.ts',
        content: `import { Hono } from 'hono';
import { createTask, listTasks } from '../services/task.service.js';
import { requireString } from '../utils/validation.js';

export const taskRoutes = new Hono();

taskRoutes.get('/', (context) =>
  context.json({ data: listTasks(), requestId: context.req.header('x-request-id') ?? 'local' }),
);

taskRoutes.post('/', async (context) => {
  const body = (await context.req.json().catch(() => ({}))) as Record<string, unknown>;
  const task = createTask(requireString(body.title, 'title'));
  return context.json({ data: task, requestId: context.req.header('x-request-id') ?? 'local' }, 201);
});
`,
      },
      {
        path: 'src/app.ts',
        content: `import { Hono } from 'hono';
import { logger } from 'hono/logger';
import { errorHandler } from './middleware/error-handler.js';
import { requestIdMiddleware } from './middleware/request-id.js';
import { healthRoutes } from './routes/health.routes.js';
import { taskRoutes } from './routes/task.routes.js';

export function createApp() {
  const app = new Hono();
  app.use('*', logger());
  app.use('*', requestIdMiddleware);
  app.onError(errorHandler);
  app.route('/api/health', healthRoutes);
  app.route('/api/tasks', taskRoutes);
  return app;
}
`,
      },
      {
        path: 'src/index.ts',
        content: `import { serve } from '@hono/node-server';
import { createApp } from './app.js';
import { env } from './config/env.js';

const server = serve({ fetch: createApp().fetch, port: env.port }, () => {
  console.log(\`\${env.appName} listening on http://localhost:\${env.port}\`);
});

for (const signal of ['SIGINT', 'SIGTERM']) {
  process.on(signal, () => {
    server.close(() => process.exit(0));
  });
}
`,
      },
    ],
  },
};
