import { PredefinedTemplateDefinition } from '../types.js';
import { commonBackendFiles, createBackendPackageJson, createReadme } from './helpers.js';

export const nestjsRestApiTemplate: PredefinedTemplateDefinition = {
  metadata: {
    id: 'nestjs-rest-api',
    name: 'NestJS REST API',
    category: 'backend',
    description:
      'NestJS REST API starter with modules, controllers, services, DTOs, pipes, filters, guards, config, and health endpoint.',
    supportedFrameworks: ['nest'],
    supportedStyling: ['none'],
    defaultFramework: 'nest',
    defaultStyling: 'none',
    generatedFiles: ['src/main.ts', 'src/app.module.ts', 'src/health', 'src/users'],
    enabledFeatures: { eslint: true, prettier: true },
    scripts: { dev: 'tsx watch src/main.ts', build: 'tsc', lint: 'eslint "src/**/*.ts"' },
    verificationExpectations: ['npm run build', 'npm run lint', 'GET /api/health'],
    sections: ['App module', 'Health module', 'Users module', 'DTOs', 'Guards', 'Filters'],
    components: [
      'AppModule',
      'HealthController',
      'UsersController',
      'ValidationPipe',
      'ApiKeyGuard',
    ],
    layoutType: 'NestJS Modular API',
    successSummary: 'Generated NestJS REST API starter.',
  },
  backendDefinition: {
    files: ({ projectName }) => [
      ...commonBackendFiles(
        projectName,
        createReadme(projectName, 'A scalable NestJS REST API generated by Structify.', [
          'GET /api/health',
          'GET /api/users',
          'POST /api/users',
        ]),
      ),
      {
        path: 'package.json',
        content: createBackendPackageJson({
          projectName,
          description: 'Structify NestJS REST API starter',
          scripts: { dev: 'npm run build && node dist/index.js' },
          dependencies: {
            '@nestjs/common': '^10.4.15',
            '@nestjs/core': '^10.4.15',
            '@nestjs/platform-express': '^10.4.15',
            dotenv: '^16.4.7',
            'reflect-metadata': '^0.2.2',
            rxjs: '^7.8.1',
          },
        }),
      },
      {
        path: 'tsconfig.json',
        content: `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "lib": ["ES2022"],
    "rootDir": "src",
    "outDir": "dist",
    "strict": true,
    "strictPropertyInitialization": false,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": ["src/**/*.ts"],
  "exclude": ["node_modules", "dist"]
}
`,
      },
      {
        path: 'src/config/env.ts',
        content: `import dotenv from 'dotenv';

dotenv.config();

export const env = {
  nodeEnv: process.env.NODE_ENV ?? 'development',
  port: Number(process.env.PORT ?? 3000),
  appName: process.env.APP_NAME ?? '${projectName}',
};
`,
      },
      {
        path: 'src/common/filters/http-exception.filter.ts',
        content: `import { ArgumentsHost, Catch, ExceptionFilter, HttpException } from '@nestjs/common';

@Catch()
export class HttpExceptionFilter implements ExceptionFilter {
  catch(exception: unknown, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const response = ctx.getResponse<{ status: (code: number) => { json: (body: unknown) => void } }>();
    const request = ctx.getRequest<{ url: string; headers: Record<string, string | undefined> }>();
    const status = exception instanceof HttpException ? exception.getStatus() : 500;
    const message = exception instanceof Error ? exception.message : 'Internal server error';

    response.status(status).json({
      error: {
        code: status === 500 ? 'INTERNAL_SERVER_ERROR' : 'REQUEST_ERROR',
        message,
      },
      requestId: request.headers['x-request-id'] ?? 'local',
      path: request.url,
    });
  }
}
`,
      },
      {
        path: 'src/common/guards/api-key.guard.ts',
        content: `import { CanActivate, ExecutionContext, Injectable } from '@nestjs/common';

@Injectable()
export class ApiKeyGuard implements CanActivate {
  canActivate(context: ExecutionContext): boolean {
    const request = context.switchToHttp().getRequest<{ headers: Record<string, string | undefined> }>();
    return Boolean(request.headers['x-demo-api-key'] ?? true);
  }
}
`,
      },
      {
        path: 'src/common/pipes/trim-body.pipe.ts',
        content: `import { ArgumentMetadata, Injectable, PipeTransform } from '@nestjs/common';

@Injectable()
export class TrimBodyPipe implements PipeTransform {
  transform(value: unknown, _metadata: ArgumentMetadata) {
    if (!value || typeof value !== 'object' || Array.isArray(value)) {
      return value;
    }
    return Object.fromEntries(
      Object.entries(value).map(([key, entry]) => [
        key,
        typeof entry === 'string' ? entry.trim() : entry,
      ]),
    );
  }
}
`,
      },
      {
        path: 'src/health/health.service.ts',
        content: `import { Injectable } from '@nestjs/common';
import { env } from '../config/env.js';
import { HealthStatus } from '../interfaces/health.interface.js';

@Injectable()
export class HealthService {
  getHealth(): HealthStatus {
    return {
      status: 'ok',
      uptime: process.uptime(),
      timestamp: new Date().toISOString(),
      service: env.appName,
    };
  }
}
`,
      },
      {
        path: 'src/health/health.controller.ts',
        content: `import { Controller, Get } from '@nestjs/common';
import { HealthService } from './health.service.js';

@Controller('health')
export class HealthController {
  constructor(private readonly healthService: HealthService) {}

  @Get()
  getHealth() {
    return { data: this.healthService.getHealth(), requestId: 'local' };
  }
}
`,
      },
      {
        path: 'src/health/health.module.ts',
        content: `import { Module } from '@nestjs/common';
import { HealthController } from './health.controller.js';
import { HealthService } from './health.service.js';

@Module({
  controllers: [HealthController],
  providers: [HealthService],
})
export class HealthModule {}
`,
      },
      {
        path: 'src/users/dto/create-user.dto.ts',
        content: `export class CreateUserDto {
  name!: string;
  email!: string;
}
`,
      },
      {
        path: 'src/users/users.service.ts',
        content: `import { Injectable, NotFoundException } from '@nestjs/common';
import { CreateUserDto } from './dto/create-user.dto.js';

export interface User {
  id: string;
  name: string;
  email: string;
}

@Injectable()
export class UsersService {
  private readonly users: User[] = [
    { id: 'usr_001', name: 'Demo Admin', email: 'admin@example.test' },
  ];

  findAll() {
    return this.users;
  }

  findOne(id: string) {
    const user = this.users.find((item) => item.id === id);
    if (!user) {
      throw new NotFoundException('User was not found.');
    }
    return user;
  }

  create(input: CreateUserDto) {
    const user = { id: \`usr_\${String(this.users.length + 1).padStart(3, '0')}\`, ...input };
    this.users.push(user);
    return user;
  }
}
`,
      },
      {
        path: 'src/users/users.controller.ts',
        content: `import { Body, Controller, Get, Param, Post, UseGuards, UsePipes } from '@nestjs/common';
import { ApiKeyGuard } from '../common/guards/api-key.guard.js';
import { TrimBodyPipe } from '../common/pipes/trim-body.pipe.js';
import { CreateUserDto } from './dto/create-user.dto.js';
import { UsersService } from './users.service.js';

@Controller('users')
@UseGuards(ApiKeyGuard)
export class UsersController {
  constructor(private readonly usersService: UsersService) {}

  @Get()
  findAll() {
    return { data: this.usersService.findAll(), requestId: 'local' };
  }

  @Get(':id')
  findOne(@Param('id') id: string) {
    return { data: this.usersService.findOne(id), requestId: 'local' };
  }

  @Post()
  @UsePipes(TrimBodyPipe)
  create(@Body() input: CreateUserDto) {
    return { data: this.usersService.create(input), requestId: 'local' };
  }
}
`,
      },
      {
        path: 'src/users/users.module.ts',
        content: `import { Module } from '@nestjs/common';
import { UsersController } from './users.controller.js';
import { UsersService } from './users.service.js';

@Module({
  controllers: [UsersController],
  providers: [UsersService],
})
export class UsersModule {}
`,
      },
      {
        path: 'src/routes/index.ts',
        content: `export const routePrefixes = {
  health: 'api/health',
  users: 'api/users',
} as const;
`,
      },
      {
        path: 'src/services/index.ts',
        content: `export { HealthService } from '../health/health.service.js';
export { UsersService } from '../users/users.service.js';
`,
      },
      {
        path: 'src/app.module.ts',
        content: `import { Module } from '@nestjs/common';
import { HealthModule } from './health/health.module.js';
import { UsersModule } from './users/users.module.js';

@Module({
  imports: [HealthModule, UsersModule],
})
export class AppModule {}
`,
      },
      {
        path: 'src/main.ts',
        content: `import 'reflect-metadata';
import { NestFactory } from '@nestjs/core';
import { HttpExceptionFilter } from './common/filters/http-exception.filter.js';
import { env } from './config/env.js';
import { AppModule } from './app.module.js';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.setGlobalPrefix('api');
  app.useGlobalFilters(new HttpExceptionFilter());
  await app.listen(env.port);
  console.log(\`\${env.appName} listening on http://localhost:\${env.port}\`);
}

void bootstrap();
`,
      },
      {
        path: 'src/index.ts',
        content: `import './main.js';
`,
      },
    ],
  },
};
