import { PredefinedTemplateDefinition } from '../types.js';
import { commonBackendFiles, createBackendPackageJson, createReadme } from './helpers.js';

export const nodeAuthApiTemplate: PredefinedTemplateDefinition = {
  metadata: {
    id: 'node-auth-api',
    name: 'Node.js Authentication API',
    category: 'backend',
    description:
      'Express authentication API with JWT login/register, password hashing, auth middleware, refresh token mock flow, and protected routes.',
    supportedFrameworks: ['node-auth', 'express'],
    supportedStyling: ['none'],
    defaultFramework: 'node-auth',
    defaultStyling: 'none',
    generatedFiles: ['src/auth', 'src/controllers', 'src/routes', 'src/middleware'],
    enabledFeatures: { eslint: true, prettier: true },
    scripts: { dev: 'tsx watch src/index.ts', build: 'tsc', lint: 'eslint "src/**/*.ts"' },
    verificationExpectations: ['npm run build', 'npm run lint', 'GET /api/health'],
    sections: [
      'Register endpoint',
      'Login endpoint',
      'Refresh token flow',
      'JWT middleware',
      'Protected route',
    ],
    components: [
      'AuthService',
      'AuthController',
      'AuthMiddleware',
      'TokenService',
      'ProtectedRoutes',
    ],
    layoutType: 'Express Auth API',
    successSummary: 'Generated Node.js authentication API starter.',
  },
  backendDefinition: {
    files: ({ projectName }) => [
      ...commonBackendFiles(
        projectName,
        createReadme(projectName, 'A JWT authentication API starter generated by Structify.', [
          'GET /api/health',
          'POST /api/auth/register',
          'POST /api/auth/login',
          'POST /api/auth/refresh',
          'GET /api/profile',
        ]),
      ),
      {
        path: '.env.example',
        content: `NODE_ENV=development
PORT=3000
APP_NAME=${projectName}
JWT_SECRET=replace-with-a-local-development-secret
JWT_EXPIRES_IN=15m
`,
      },
      {
        path: 'package.json',
        content: createBackendPackageJson({
          projectName,
          description: 'Structify Node.js authentication API starter',
          scripts: {},
          dependencies: {
            bcryptjs: '^2.4.3',
            cors: '^2.8.5',
            dotenv: '^16.4.7',
            express: '^4.21.2',
            helmet: '^7.2.0',
            jsonwebtoken: '^9.0.2',
          },
          devDependencies: {
            '@types/bcryptjs': '^2.4.6',
            '@types/cors': '^2.8.17',
            '@types/express': '^4.17.21',
            '@types/jsonwebtoken': '^9.0.7',
          },
        }),
      },
      {
        path: 'src/config/env.ts',
        content: `import dotenv from 'dotenv';

dotenv.config();

export const env = {
  nodeEnv: process.env.NODE_ENV ?? 'development',
  port: Number(process.env.PORT ?? 3000),
  appName: process.env.APP_NAME ?? '${projectName}',
  jwtSecret: process.env.JWT_SECRET ?? 'local-development-secret',
  jwtExpiresIn: process.env.JWT_EXPIRES_IN ?? '15m',
};
`,
      },
      {
        path: 'src/auth/auth.types.ts',
        content: `export interface AuthUser {
  id: string;
  email: string;
  name: string;
  passwordHash: string;
}

export interface PublicUser {
  id: string;
  email: string;
  name: string;
}

export interface TokenPair {
  accessToken: string;
  refreshToken: string;
}
`,
      },
      {
        path: 'src/types/express.d.ts',
        content: `import { PublicUser } from '../auth/auth.types.js';

declare global {
  namespace Express {
    interface Request {
      user?: PublicUser;
    }
  }
}
`,
      },
      {
        path: 'src/auth/token.service.ts',
        content: `import jwt, { SignOptions } from 'jsonwebtoken';
import { env } from '../config/env.js';
import { PublicUser, TokenPair } from './auth.types.js';

const refreshTokens = new Map<string, string>();

export function createTokenPair(user: PublicUser): TokenPair {
  const expiresIn = env.jwtExpiresIn as SignOptions['expiresIn'];
  const accessToken = jwt.sign({ sub: user.id, email: user.email, name: user.name }, env.jwtSecret, {
    expiresIn,
  });
  const refreshToken = crypto.randomUUID();
  refreshTokens.set(refreshToken, user.id);
  return { accessToken, refreshToken };
}

export function verifyAccessToken(token: string): PublicUser {
  const payload = jwt.verify(token, env.jwtSecret) as { sub: string; email: string; name: string };
  return { id: payload.sub, email: payload.email, name: payload.name };
}

export function consumeRefreshToken(refreshToken: string) {
  return refreshTokens.get(refreshToken);
}
`,
      },
      {
        path: 'src/auth/auth.service.ts',
        content: `import bcrypt from 'bcryptjs';
import { AuthUser, PublicUser } from './auth.types.js';
import { consumeRefreshToken, createTokenPair } from './token.service.js';

const users: AuthUser[] = [];

function toPublicUser(user: AuthUser): PublicUser {
  return { id: user.id, email: user.email, name: user.name };
}

export class AuthService {
  async register(input: { email: string; name: string; password: string }) {
    if (users.some((user) => user.email === input.email)) {
      throw new Error('Email is already registered.');
    }
    const user = {
      id: \`usr_\${String(users.length + 1).padStart(3, '0')}\`,
      email: input.email,
      name: input.name,
      passwordHash: await bcrypt.hash(input.password, 10),
    };
    users.push(user);
    return { user: toPublicUser(user), tokens: createTokenPair(toPublicUser(user)) };
  }

  async login(input: { email: string; password: string }) {
    const user = users.find((item) => item.email === input.email);
    if (!user || !(await bcrypt.compare(input.password, user.passwordHash))) {
      throw new Error('Invalid email or password.');
    }
    return { user: toPublicUser(user), tokens: createTokenPair(toPublicUser(user)) };
  }

  refresh(refreshToken: string) {
    const userId = consumeRefreshToken(refreshToken);
    const user = users.find((item) => item.id === userId);
    if (!user) {
      throw new Error('Refresh token is invalid or expired.');
    }
    return { user: toPublicUser(user), tokens: createTokenPair(toPublicUser(user)) };
  }
}
`,
      },
      {
        path: 'src/services/index.ts',
        content: `export { AuthService } from '../auth/auth.service.js';
`,
      },
      {
        path: 'src/utils/validation.ts',
        content: `export function requireString(value: unknown, field: string): string {
  if (typeof value !== 'string' || value.trim().length === 0) {
    throw new Error(\`\${field} is required.\`);
  }
  return value.trim();
}
`,
      },
      {
        path: 'src/middleware/auth.middleware.ts',
        content: `import { NextFunction, Request, Response } from 'express';
import { verifyAccessToken } from '../auth/token.service.js';

export function requireAuth(req: Request, res: Response, next: NextFunction) {
  const header = req.headers.authorization;
  const token = header?.startsWith('Bearer ') ? header.slice('Bearer '.length) : undefined;
  if (!token) {
    res.status(401).json({ error: { code: 'UNAUTHORIZED', message: 'Bearer token is required.' } });
    return;
  }
  try {
    req.user = verifyAccessToken(token);
    next();
  } catch {
    res.status(401).json({ error: { code: 'INVALID_TOKEN', message: 'Bearer token is invalid.' } });
  }
}
`,
      },
      {
        path: 'src/middleware/error-handler.ts',
        content: `import { NextFunction, Request, Response } from 'express';

export function errorHandler(error: Error, req: Request, res: Response, _next: NextFunction) {
  res.status(400).json({
    error: { code: 'REQUEST_ERROR', message: error.message },
    requestId: req.headers['x-request-id'] ?? 'local',
  });
}
`,
      },
      {
        path: 'src/middleware/request-logger.ts',
        content: `import { NextFunction, Request, Response } from 'express';

export function requestLogger(req: Request, res: Response, next: NextFunction) {
  const startedAt = Date.now();
  res.on('finish', () => {
    console.log(\`\${req.method} \${req.originalUrl} \${res.statusCode} \${Date.now() - startedAt}ms\`);
  });
  next();
}
`,
      },
      {
        path: 'src/controllers/auth.controller.ts',
        content: `import { Request, Response } from 'express';
import { AuthService } from '../auth/auth.service.js';
import { requireString } from '../utils/validation.js';

const authService = new AuthService();

export async function register(req: Request, res: Response) {
  const body = req.body as Record<string, unknown>;
  const result = await authService.register({
    email: requireString(body.email, 'email'),
    name: requireString(body.name, 'name'),
    password: requireString(body.password, 'password'),
  });
  res.status(201).json({ data: result, requestId: req.headers['x-request-id'] ?? 'local' });
}

export async function login(req: Request, res: Response) {
  const body = req.body as Record<string, unknown>;
  const result = await authService.login({
    email: requireString(body.email, 'email'),
    password: requireString(body.password, 'password'),
  });
  res.json({ data: result, requestId: req.headers['x-request-id'] ?? 'local' });
}

export function refresh(req: Request, res: Response) {
  const body = req.body as Record<string, unknown>;
  const result = authService.refresh(requireString(body.refreshToken, 'refreshToken'));
  res.json({ data: result, requestId: req.headers['x-request-id'] ?? 'local' });
}
`,
      },
      {
        path: 'src/controllers/health.controller.ts',
        content: `import { Request, Response } from 'express';
import { env } from '../config/env.js';

export function getHealth(req: Request, res: Response) {
  res.json({
    data: { status: 'ok', uptime: process.uptime(), timestamp: new Date().toISOString(), service: env.appName },
    requestId: req.headers['x-request-id'] ?? 'local',
  });
}
`,
      },
      {
        path: 'src/controllers/profile.controller.ts',
        content: `import { Request, Response } from 'express';

export function getProfile(req: Request, res: Response) {
  res.json({ data: req.user, requestId: req.headers['x-request-id'] ?? 'local' });
}
`,
      },
      {
        path: 'src/routes/auth.routes.ts',
        content: `import { Router } from 'express';
import { login, refresh, register } from '../controllers/auth.controller.js';

export const authRouter = Router();

authRouter.post('/register', (req, res, next) => void register(req, res).catch(next));
authRouter.post('/login', (req, res, next) => void login(req, res).catch(next));
authRouter.post('/refresh', refresh);
`,
      },
      {
        path: 'src/routes/health.routes.ts',
        content: `import { Router } from 'express';
import { getHealth } from '../controllers/health.controller.js';

export const healthRouter = Router();

healthRouter.get('/health', getHealth);
`,
      },
      {
        path: 'src/routes/profile.routes.ts',
        content: `import { Router } from 'express';
import { getProfile } from '../controllers/profile.controller.js';
import { requireAuth } from '../middleware/auth.middleware.js';

export const profileRouter = Router();

profileRouter.get('/profile', requireAuth, getProfile);
`,
      },
      {
        path: 'src/app.ts',
        content: `import cors from 'cors';
import express from 'express';
import helmet from 'helmet';
import { errorHandler } from './middleware/error-handler.js';
import { requestLogger } from './middleware/request-logger.js';
import { authRouter } from './routes/auth.routes.js';
import { healthRouter } from './routes/health.routes.js';
import { profileRouter } from './routes/profile.routes.js';

export function createApp() {
  const app = express();
  app.use(helmet());
  app.use(cors());
  app.use(express.json());
  app.use(requestLogger);
  app.use('/api', healthRouter);
  app.use('/api/auth', authRouter);
  app.use('/api', profileRouter);
  app.use(errorHandler);
  return app;
}
`,
      },
      {
        path: 'src/index.ts',
        content: `import { createServer } from 'node:http';
import { createApp } from './app.js';
import { env } from './config/env.js';

const server = createServer(createApp());

server.listen(env.port, () => {
  console.log(\`\${env.appName} listening on http://localhost:\${env.port}\`);
});

for (const signal of ['SIGINT', 'SIGTERM']) {
  process.on(signal, () => {
    server.close(() => process.exit(0));
  });
}
`,
      },
    ],
  },
};
