import { PluginDefinition } from './sdk.js';
import { getStarterTemplates } from '../templates/templates.js';

export function createBuiltInExtensionPlugin(): PluginDefinition {
  return {
    metadata: {
      id: 'structify-builtins',
      name: 'Structify Built-in Extension Pack',
      version: '1.0.0',
      author: 'Structify Team',
      description: 'Provides the Phase 7 internal generators, templates, and modules.',
      supportedStructifyVersion: '>=1.0.0',
      status: 'stable',
      providedGenerators: [
        'gen-next',
        'gen-vite-react',
        'gen-express',
        'gen-nest',
        'gen-tailwind',
        'gen-mui',
        'gen-prisma',
        'gen-mongoose',
        'gen-docker',
        'gen-github-actions',
        'gen-eslint',
        'gen-prettier',
      ],
      providedTemplates: ['tmpl-phase7-starter-batch'],
      providedModules: ['mod-tailwind', 'mod-docker', 'mod-prisma'],
    },
    generators: [
      {
        id: 'gen-phase7-deterministic',
        name: 'Phase 7 Deterministic Generator',
        description: 'Delegates existing MVP deterministic templates through the Generator SDK.',
        version: '1.0.0',
        status: 'stable',
        supportedStacks: [
          'next',
          'vite-react',
          'express',
          'nest',
          'tailwind',
          'mui',
          'prisma',
          'mongoose',
        ],
        supportedModes: ['frontend-only', 'backend-only', 'fullstack'],
        requiredTemplates: ['tmpl-phase7-starter-batch'],
        generateFiles: (config) => getStarterTemplates(config),
      },
    ],
    templates: [
      {
        id: 'tmpl-phase7-starter-batch',
        name: 'Phase 7 Starter Template Batch',
        description: 'Template SDK descriptor for deterministic starter files.',
        version: '1.0.0',
        status: 'stable',
        requiredVariables: ['projectName'],
        targetPath: 'structify.config.json',
        supportedModes: ['frontend-only', 'backend-only', 'fullstack'],
        render: (variables) => JSON.stringify({ projectName: variables.projectName }, null, 2),
      },
    ],
    modules: [
      {
        id: 'mod-tailwind',
        name: 'Tailwind CSS Module',
        description: 'Future incremental Tailwind module contract.',
        version: '1.0.0',
        status: 'stable',
        supportedProjectTypes: ['frontend-only', 'fullstack'],
        detectionRules: ['tailwind.config.js', 'postcss.config.js'],
        conflictPolicy: 'error',
        rollbackStrategy: 'remove-generated-files',
      },
      {
        id: 'mod-docker',
        name: 'Docker Module',
        description: 'Future incremental Docker module contract.',
        version: '1.0.0',
        status: 'stable',
        supportedProjectTypes: ['frontend-only', 'backend-only', 'fullstack'],
        detectionRules: ['Dockerfile', 'docker-compose.yml'],
        conflictPolicy: 'error',
        rollbackStrategy: 'remove-generated-files',
      },
      {
        id: 'mod-prisma',
        name: 'Prisma Module',
        description: 'Future incremental Prisma module contract.',
        version: '1.0.0',
        status: 'stable',
        supportedProjectTypes: ['backend-only', 'fullstack'],
        detectionRules: ['prisma/schema.prisma'],
        conflictPolicy: 'error',
        rollbackStrategy: 'remove-generated-files',
      },
    ],
  };
}
